CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	username TEXT NOT NULL UNIQUE,
	hash TEXT NOT NULL,
	account_balance TEXT DEFAULT "10000" NOT NULL
);

CREATE TABLE portfolios (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user_id INTEGER NOT NULL,
	ticker TEXT NOT NULL,
	size TEXT DEFAULT 0,
	entry_price TEXT DEFAULT 0,
	total_value TEXT DEFAULT 0,
	FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE txns (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	txn_type TEXT NOT NULL,
	portfolio_id INTEGER NOT NULL,
	size TEXT NOT NULL,
	traded_price TEXT NOT NULL,
	total_value TEXT NOT NULL,
	pre_balance TEXT NOT NULL,
	post_balance TEXT NOT NULL,
	FOREIGN KEY(portfolio_id) REFERENCES portfolios(id)
);